"use client";

import React, { useEffect, useState } from 'react';
import KPICard from './KPICard';
import PivotTable from './PivotTable';
import {
    Chart as ChartJS,
    CategoryScale,
    LinearScale,
    PointElement,
    LineElement,
    BarElement,
    Title,
    Tooltip,
    Legend,
    ArcElement,
    ChartOptions,
    ChartData,
    Filler,
    RadialLinearScale,
} from 'chart.js';
import { Bar, Line, Pie, Doughnut, Scatter, Radar, PolarArea } from 'react-chartjs-2';
import ChartDataLabels from 'chartjs-plugin-datalabels';
import { TechnicalBadge } from './PaperAccents';

ChartJS.register(
    CategoryScale,
    LinearScale,
    PointElement,
    LineElement,
    BarElement,
    Title,
    Tooltip,
    Legend,
    ArcElement,
    Filler,
    RadialLinearScale,
);

// Register datalabels globally but disable by default (enable per-chart)
ChartJS.register(ChartDataLabels);

export type ChartType = 'bar' | 'line' | 'area' | 'pie' | 'doughnut' | 'scatter' | 'radar' | 'polarArea' | 'horizontalBar' | 'kpi' | 'matrix';

export const CHART_TYPE_OPTIONS: { value: ChartType; label: string; icon: string }[] = [
    { value: 'bar',           label: 'Bar',            icon: '📊' },
    { value: 'horizontalBar', label: 'H-Bar',          icon: '📶' },
    { value: 'line',          label: 'Line',           icon: '📈' },
    { value: 'area',          label: 'Area',           icon: '🏔️' },
    { value: 'scatter',       label: 'Scatter',        icon: '⊙' },
    { value: 'pie',           label: 'Pie',            icon: '🥧' },
    { value: 'doughnut',      label: 'Donut',          icon: '🍩' },
    { value: 'radar',         label: 'Radar',          icon: '🕸️' },
    { value: 'polarArea',     label: 'Polar',          icon: '🎯' },
    { value: 'kpi',           label: 'KPI',            icon: '#️⃣' },
    { value: 'matrix',        label: 'Matrix',         icon: '📋' },
];

interface VisualizerProps {
    type: ChartType;
    data: any[];
    labelKey: string;
    valueKey: string;
    title?: string;
    onDrillDown?: (label: string) => void;
    seriesData?: Record<string, any[]>;
    stackMode?: 'stacked' | 'grouped';
    colorByColumn?: string;
    // P4: Formatting controls
    showDataLabels?: boolean;
    showXAxis?: boolean;
    showYAxis?: boolean;
    showGridLines?: boolean;
    markerSize?: number;
    // P6: Extra tooltip metrics
    tooltipExtras?: { key: string; label: string }[];
}

function getThemeColors() {
    if (typeof window === 'undefined') return { isDark: false };
    const style = getComputedStyle(document.documentElement);
    const bg = style.getPropertyValue('--background').trim();
    const isDark = bg.startsWith('#0') || bg.startsWith('#1') || bg.startsWith('#2');
    return { isDark };
}

export default function Visualizer({ type, data, labelKey, valueKey, title = '', onDrillDown, seriesData, stackMode = 'stacked', colorByColumn, showDataLabels = false, showXAxis = true, showYAxis = true, showGridLines = true, markerSize, tooltipExtras }: VisualizerProps) {
    const [isDark, setIsDark] = useState(false);

    useEffect(() => {
        setIsDark(getThemeColors().isDark);
    }, []);

    // Blueprint-themed palette — 10 colors to cover all slices
    const blueprintPalette = [
        isDark ? 'rgba(96, 165, 250, 0.8)' : 'rgba(37, 99, 235, 0.8)',
        isDark ? 'rgba(52, 211, 153, 0.8)' : 'rgba(16, 185, 129, 0.8)',
        isDark ? 'rgba(251, 191, 36, 0.8)' : 'rgba(245, 158, 11, 0.8)',
        isDark ? 'rgba(167, 139, 250, 0.8)' : 'rgba(139, 92, 246, 0.8)',
        isDark ? 'rgba(251, 113, 133, 0.8)' : 'rgba(239, 68, 68, 0.8)',
        isDark ? 'rgba(56, 189, 248, 0.8)' : 'rgba(14, 165, 233, 0.8)',
        isDark ? 'rgba(253, 164, 175, 0.8)' : 'rgba(244, 63, 94, 0.8)',
        isDark ? 'rgba(134, 239, 172, 0.8)' : 'rgba(34, 197, 94, 0.8)',
        isDark ? 'rgba(253, 186, 116, 0.8)' : 'rgba(234, 88, 12, 0.8)',
        isDark ? 'rgba(196, 181, 253, 0.8)' : 'rgba(109, 40, 217, 0.8)',
    ];

    // Theme-aware chart colors
    const primaryColor = isDark ? 'rgba(96, 165, 250, 1)' : 'rgba(37, 99, 235, 1)';
    const primaryBg = isDark ? 'rgba(96, 165, 250, 0.65)' : 'rgba(37, 99, 235, 0.65)';
    const primaryFill = isDark ? 'rgba(96, 165, 250, 0.12)' : 'rgba(37, 99, 235, 0.06)';
    const gridColor = isDark ? 'rgba(255, 255, 255, 0.06)' : 'rgba(0, 0, 0, 0.06)';
    const borderAxisColor = isDark ? 'rgba(255, 255, 255, 0.15)' : 'rgba(0, 0, 0, 0.12)';
    const tickColor = isDark ? '#94a3b8' : '#475569';
    const pointBorderColor = isDark ? '#1e293b' : '#ffffff';

    const isRadial = type === 'pie' || type === 'doughnut' || type === 'polarArea' || type === 'radar';
    const isScatter = type === 'scatter';
    const isArea = type === 'area';
    const isHorizontal = type === 'horizontalBar';

    // Expand palette to cover all data points for multi-color charts
    // Use a muted gray for "Other" bucket (auto-generated by smart limits)
    const expandedPalette = data.map((item, i) => {
        if (item[labelKey] === 'Other') {
            return isDark ? 'rgba(100, 116, 139, 0.5)' : 'rgba(148, 163, 184, 0.5)';
        }
        return blueprintPalette[i % blueprintPalette.length];
    });

    // Build dataset(s)
    const buildDatasets = () => {
        // Multi-series mode
        if (seriesData && Object.keys(seriesData).length > 0) {
            const seriesNames = Object.keys(seriesData);
            return seriesNames.map((name, idx) => {
                const seriesColor = blueprintPalette[idx % blueprintPalette.length];
                const seriesBorder = seriesColor.replace('0.8', '1');
                const seriesItems = seriesData[name] || [];
                
                if (isRadial) {
                    return {
                        label: name,
                        data: seriesItems.map((item: any) => item[valueKey]),
                        backgroundColor: seriesColor,
                        borderColor: seriesBorder,
                        borderWidth: 2,
                    };
                }

                return {
                    label: name,
                    data: seriesItems.map((item: any) => item[valueKey]),
                    backgroundColor: seriesColor,
                    borderColor: seriesBorder,
                    borderWidth: 2,
                    borderRadius: (type === 'bar' || isHorizontal) ? 3 : 0,
                    tension: 0.35,
                    fill: false,
                    pointBackgroundColor: seriesBorder,
                    pointBorderColor: pointBorderColor,
                    pointBorderWidth: 2,
                    pointRadius: (type === 'line' || isArea) ? (markerSize ?? 3) : 0,
                    pointHoverRadius: (markerSize ?? 3) + 3,
                };
            });
        }

        // Single-series mode (original)
        if (isScatter) {
            return [{
                label: title || valueKey,
                data: data.map(item => ({ x: item[labelKey], y: item[valueKey] })),
                backgroundColor: primaryBg,
                borderColor: primaryColor,
                pointBackgroundColor: primaryColor,
                pointBorderColor: pointBorderColor,
                pointBorderWidth: 2,
                pointRadius: 5,
                pointHoverRadius: 8,
            }];
        }

        if (isRadial) {
            return [{
                label: title || valueKey,
                data: data.map(item => item[valueKey]),
                backgroundColor: expandedPalette,
                borderColor: expandedPalette.map(c => c.replace('0.8', '1')),
                borderWidth: 2,
                hoverOffset: type === 'doughnut' ? 8 : 4,
            }];
        }

        // Bar, line, area, horizontalBar
        return [{
            label: title || valueKey,
            data: data.map(item => item[valueKey]),
            backgroundColor: isArea ? primaryFill : primaryBg,
            borderColor: primaryColor,
            borderWidth: 2,
            borderRadius: (type === 'bar' || isHorizontal) ? 3 : 0,
            tension: 0.35,
            fill: isArea,
            pointBackgroundColor: primaryColor,
            pointBorderColor: pointBorderColor,
            pointBorderWidth: 2,
            pointRadius: (type === 'line' || isArea) ? (markerSize ?? 3) : 0,
            pointHoverRadius: (markerSize ?? 3) + 3,
        }];
    };

    // For multi-series, use labels from the first series
    const getLabels = () => {
        if (seriesData && Object.keys(seriesData).length > 0) {
            const firstSeries = Object.values(seriesData)[0] || [];
            return firstSeries.map((item: any) => item[labelKey]);
        }
        return data.map(item => item[labelKey]);
    };

    const chartData: ChartData<any> = {
        labels: getLabels(),
        datasets: buildDatasets(),
    };

    const monoFont = 'ui-monospace, SFMono-Regular, monospace';

    const tooltipConfig = {
        backgroundColor: isDark ? 'rgba(15, 23, 42, 0.95)' : 'rgba(30, 41, 59, 0.95)',
        padding: 12,
        titleFont: { size: 12, family: monoFont, weight: 'bold' as const },
        bodyFont: { size: 13, family: monoFont },
        cornerRadius: 4,
        displayColors: true,
        boxPadding: 6,
        borderColor: isDark ? 'rgba(96, 165, 250, 0.3)' : 'rgba(37, 99, 235, 0.2)',
        borderWidth: 1,
        titleColor: '#f8fafc',
        bodyColor: '#e2e8f0',
    };

    const legendConfig = {
        display: isRadial || (seriesData && Object.keys(seriesData).length > 0),
        position: 'bottom' as const,
        labels: {
            usePointStyle: true,
            padding: 14,
            font: { family: monoFont, size: 12, weight: 'bold' as const },
            color: tickColor,
        },
    };

    const scaleConfig = (!isRadial && !isScatter) ? {
        y: {
            display: showYAxis,
            beginAtZero: true,
            stacked: (seriesData && Object.keys(seriesData).length > 0 && stackMode === 'stacked') ? true : false,
            border: { display: true, color: borderAxisColor, width: 1 },
            grid: { display: showGridLines, color: gridColor, lineWidth: 1 },
            ticks: {
                font: { family: monoFont, size: 12 },
                color: tickColor,
                padding: 8,
                maxTicksLimit: 8,
            },
        },
        x: {
            display: showXAxis,
            stacked: (seriesData && Object.keys(seriesData).length > 0 && stackMode === 'stacked') ? true : false,
            border: { display: true, color: borderAxisColor, width: 1 },
            grid: { display: false },
            ticks: {
                font: { family: monoFont, size: 12 },
                color: tickColor,
                padding: 8,
                maxRotation: 45,
                autoSkip: true,
                maxTicksLimit: 20,
            },
        },
    } : (type === 'radar' ? {
        r: {
            beginAtZero: true,
            grid: { color: gridColor },
            angleLines: { color: gridColor },
            pointLabels: {
                font: { family: monoFont, size: 12 },
                color: tickColor,
            },
            ticks: {
                font: { family: monoFont, size: 11 },
                color: tickColor,
                backdropColor: 'transparent',
            },
        },
    } : undefined);

    // Build tooltip callbacks for extras (P6)
    const tooltipCallbacks = tooltipExtras && tooltipExtras.length > 0 ? {
        afterBody: (context: any[]) => {
            if (!context.length) return '';
            const idx = context[0].dataIndex;
            const dataRow = data[idx];
            if (!dataRow) return '';
            return tooltipExtras.map(extra => {
                const val = dataRow[extra.key];
                return `${extra.label}: ${val != null ? val : '—'}`;
            }).join('\n');
        },
    } : {};

    const resolvedTooltipConfig = {
        ...tooltipConfig,
        callbacks: tooltipCallbacks,
    };

    // Datalabels config — shows on pie/doughnut always, on other charts when showDataLabels=true
    const datalabelsConfig = (type === 'pie' || type === 'doughnut') ? {
            color: tickColor,
            font: { family: monoFont, size: 11, weight: 'bold' as const },
            formatter: (value: number, ctx: any) => {
                const dataset = ctx.chart.data.datasets[0];
                const total = dataset.data.reduce((a: number, b: number) => a + b, 0);
                const pct = total > 0 ? ((value / total) * 100).toFixed(1) + '%' : '';
                const label = ctx.chart.data.labels?.[ctx.dataIndex] || '';
                if (total > 0 && (value / total) < 0.05) return '';
                return `${label}\n${pct}`;
            },
            anchor: 'end' as const,
            align: 'start' as const,
            offset: 2,
            clamp: true,
        } : showDataLabels ? {
            color: tickColor,
            font: { family: monoFont, size: 11, weight: 'bold' as const },
            anchor: 'end' as const,
            align: 'top' as const,
            offset: 4,
            formatter: (value: number) => {
                if (value == null) return '';
                const abs = Math.abs(value);
                if (abs >= 1_000_000) return (value / 1_000_000).toFixed(1) + 'M';
                if (abs >= 1_000) return (value / 1_000).toFixed(1) + 'K';
                if (Number.isInteger(value)) return value.toLocaleString();
                return value.toFixed(1);
            },
        } : { display: false };

    const options: ChartOptions<any> = {
        responsive: true,
        maintainAspectRatio: false,
        indexAxis: isHorizontal ? 'y' as const : 'x' as const,
        plugins: {
            legend: legendConfig,
            title: { display: false },
            tooltip: resolvedTooltipConfig,
            datalabels: datalabelsConfig,
        },
        scales: scaleConfig,
        animation: { duration: 800, easing: 'easeOutQuart' as const },
        ...(type === 'doughnut' ? { cutout: '55%' } : {}),
        ...(onDrillDown ? {
            onClick: (_event: any, elements: any[]) => {
                if (elements.length > 0) {
                    const idx = elements[0].index;
                    const labels = data.map(item => String(item[labelKey] ?? ''));
                    if (labels[idx]) {
                        onDrillDown(labels[idx]);
                    }
                }
            },
            onHover: (_event: any, elements: any[], chart: any) => {
                chart.canvas.style.cursor = elements.length > 0 ? 'pointer' : 'default';
            },
        } : {}),
    };

    // Map the chart type to the correct component
    const renderChart = () => {
        if (!data || data.length === 0) {
            return (
                <div className="flex items-center justify-center h-full text-(--brand-secondary) font-bold uppercase text-xs">
                    NO DATA AVAILABLE
                </div>
            );
        }

        // KPI Card — render big number
        if (type === 'kpi') {
            const totalValue = data.reduce((sum: number, item: any) => sum + (Number(item[valueKey]) || 0), 0);
            return (
                <div className="flex items-center justify-center h-full">
                    <KPICard
                        value={totalValue}
                        label={title || `${valueKey}`}
                        format="number"
                    />
                </div>
            );
        }

        // Matrix / Pivot — render when we have series data or at least 2D data
        if (type === 'matrix') {
            if (seriesData && colorByColumn) {
                // Flatten series data into rows for pivot
                const flatRows: any[] = [];
                for (const [seriesName, items] of Object.entries(seriesData)) {
                    for (const item of items) {
                        flatRows.push({ ...item, [colorByColumn]: seriesName });
                    }
                }
                return (
                    <PivotTable
                        data={flatRows}
                        rowKey={labelKey}
                        colKey={colorByColumn}
                        valueKey={valueKey}
                        title={title}
                    />
                );
            }
            // Fallback: show data as simple table
            return (
                <div className="overflow-auto h-full">
                    <table className="w-full font-mono text-xs border-collapse">
                        <thead>
                            <tr>
                                <th className="text-left p-2 border-b-2 border-(--border-color) text-[10px] text-(--brand-secondary) uppercase">{labelKey}</th>
                                <th className="text-right p-2 border-b-2 border-(--border-color) text-[10px] text-(--brand-secondary) uppercase">{valueKey}</th>
                            </tr>
                        </thead>
                        <tbody>
                            {data.map((row: any, i: number) => (
                                <tr key={i} className="hover:bg-(--surface-hover) transition-colors">
                                    <td className="p-2 border-b border-(--border-color) text-(--foreground)">{row[labelKey]}</td>
                                    <td className="p-2 border-b border-(--border-color) text-(--foreground) text-right tabular-nums">{row[valueKey]}</td>
                                </tr>
                            ))}
                        </tbody>
                    </table>
                </div>
            );
        }
        switch (type) {
            case 'bar':
            case 'horizontalBar':
                return <Bar data={chartData} options={options} />;
            case 'line':
            case 'area':
                return <Line data={chartData} options={options} />;
            case 'pie':
                return <Pie data={chartData} options={options} />;
            case 'doughnut':
                return <Doughnut data={chartData} options={options} />;
            case 'scatter':
                return <Scatter data={chartData} options={options} />;
            case 'radar':
                return <Radar data={chartData} options={options} />;
            case 'polarArea':
                return <PolarArea data={chartData} options={options} />;
            default:
                return <Bar data={chartData} options={options} />;
        }
    };

    // Resolve display label for the badge
    const badgeLabel = CHART_TYPE_OPTIONS.find(o => o.value === type)?.label.toUpperCase() || type.toUpperCase();

    return (
        <div className="w-full h-full flex flex-col p-1 font-mono text-xs">
            <div className="flex justify-between items-center mb-3">
                <div>
                    <h3 className="text-sm font-bold text-(--foreground) uppercase tracking-widest">{title}</h3>
                    <p className="text-[10px] text-(--brand-secondary)">VISUAL VECTOR SPECS</p>
                </div>
                <TechnicalBadge text={badgeLabel} status="blueprint" />
            </div>
            <div className="flex-1 relative min-h-75">
                {renderChart()}
            </div>
        </div>
    );
}
